### ISSUE TITLE
React aliases don't seem to work

### ISSUE THREAD

**Issue by JeffreyATW** [brillout/vike-preact-server-routing#1]
I have a Redux-powered Preact SSR app that I'm trying to move over to Vike.

I went ahead and installed `react-redux` into this boilerplate library, and surrounded the `PageShell` in a `<Provider>` element.

I get this error:
```Error when evaluating SSR module /renderer/PageShell.jsx: failed to import "react-redux"
|- Error: Cannot find module 'react'
Require stack:
- /Users/jeffreyatw/Code/Repos/vike-preact-server-routing/node_modules/use-sync-external-store/cjs/use-sync-external-store-shim.development.js
- /Users/jeffreyatw/Code/Repos/vike-preact-server-routing/node_modules/use-sync-external-store/shim/index.js
- /Users/jeffreyatw/Code/Repos/vike-preact-server-routing/node_modules/react-redux/lib/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Function.Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /Users/jeffreyatw/Code/Repos/vike-preact-server-routing/node_modules/use-sync-external-store/cjs/use-sync-external-store-shim.development.js:26:23
    at Object.<anonymous> (/Users/jeffreyatw/Code/Repos/vike-preact-server-routing/node_modules/use-sync-external-store/cjs/use-sync-external-store-shim.development.js:238:5)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Function.Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/jeffreyatw/Code/Repos/vike-preact-server-routing/node_modules/use-sync-external-store/shim/index.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Function.Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/jeffreyatw/Code/Repos/vike-preact-server-routing/node_modules/react-redux/lib/index.js:14:13)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Function.Module._load (node:internal/modules/cjs/loader:930:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

I would have expected `@preact/preset-vite` to handle React aliases for me, but it doesn't seem to work. Any thoughts?

**Comment by JeffreyATW** [comment]
Looks like the answer is here: https://github.com/vikejs/vike/discussions/1071

**Comment by brillout** [comment]
Thanks for circling back on this.

Btw. would your company eventually be up for [sponsoring](https://github.com/sponsors/brillout)?
